[package]
name = "stockbit-chatbot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0", default-features = false }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.140"
dotenvy="0.15.7"
request-http-parser = "0.1.0"
